import { Atmosphere } from '@/store/workspaceStore';

/**
 * Curated preset atmospheres designed to evoke specific emotions
 * through precise color tints and subtle typography shifts.
 */
export const ATMOSPHERE_PRESETS: Atmosphere[] = [
    {
        id: 'preset-slow-burn',
        name: 'Slow Burn',
        icon: '🕯️',
        lightBackground: '#F5EDE8',
        darkBackground: '#1A1008',
        soundType: 'warm-loop',
        soundVolume: 0.35,
        lineHeightShift: 0.1,
        letterSpacingShift: 0.02,
        isPreset: true,
        projectId: null,
        createdAt: new Date('2026-01-01')
    },
    {
        id: 'preset-something-breaks',
        name: 'Something Breaks',
        icon: '⚡',
        lightBackground: '#F0EEF5',
        darkBackground: '#0D0D14',
        soundType: 'silence',
        soundVolume: 0,
        lineHeightShift: 0,
        letterSpacingShift: 0,
        isPreset: true,
        projectId: null,
        createdAt: new Date('2026-01-01')
    },
    {
        id: 'preset-calm-before',
        name: 'The Calm Before',
        icon: '🌫️',
        lightBackground: '#EBF0F5',
        darkBackground: '#0A0F14',
        soundType: 'brown-noise',
        soundVolume: 0.3,
        lineHeightShift: 0.15,
        letterSpacingShift: 0.02,
        isPreset: true,
        projectId: null,
        createdAt: new Date('2026-01-01')
    },
    {
        id: 'preset-new-world',
        name: 'New World',
        icon: '🌄',
        lightBackground: '#EAF5EE',
        darkBackground: '#081410',
        soundType: 'cafe-ambient',
        soundVolume: 0.4,
        lineHeightShift: 0,
        letterSpacingShift: 0,
        isPreset: true,
        projectId: null,
        createdAt: new Date('2026-01-01')
    },
    {
        id: 'preset-grief-sits-heavy',
        name: 'Grief Sits Heavy',
        icon: '🌧️',
        lightBackground: '#EDEEF2',
        darkBackground: '#0A0B10',
        soundType: 'silence',
        soundVolume: 0,
        lineHeightShift: 0.15,
        letterSpacingShift: 0.03,
        isPreset: true,
        projectId: null,
        createdAt: new Date('2026-01-01')
    },
    {
        id: 'preset-chase-scene',
        name: 'Chase Scene',
        icon: '💨',
        lightBackground: '#F5F0EA',
        darkBackground: '#0F0A00',
        soundType: 'energetic-loop',
        soundVolume: 0.4,
        lineHeightShift: -0.1,
        letterSpacingShift: 0,
        isPreset: true,
        projectId: null,
        createdAt: new Date('2026-01-01')
    },
    {
        id: 'preset-tender-moment',
        name: 'Tender Moment',
        icon: '🌸',
        lightBackground: '#F5EDF2',
        darkBackground: '#140810',
        soundType: 'silence',
        soundVolume: 0,
        lineHeightShift: 0.1,
        letterSpacingShift: 0.02,
        isPreset: true,
        projectId: null,
        createdAt: new Date('2026-01-01')
    },
    {
        id: 'preset-somethings-wrong',
        name: "Something's Wrong",
        icon: '🕸️',
        lightBackground: '#EEECEA',
        darkBackground: '#100D08',
        soundType: 'brown-noise',
        soundVolume: 0.25,
        lineHeightShift: 0,
        letterSpacingShift: 0,
        isPreset: true,
        projectId: null,
        createdAt: new Date('2026-01-01')
    },
    {
        id: 'preset-discovery',
        name: 'Discovery',
        icon: '✨',
        lightBackground: '#EAF2F5',
        darkBackground: '#081014',
        soundType: 'cafe-ambient',
        soundVolume: 0.35,
        lineHeightShift: 0,
        letterSpacingShift: 0,
        isPreset: true,
        projectId: null,
        createdAt: new Date('2026-01-01')
    },
    {
        id: 'preset-aftermath',
        name: 'Aftermath',
        icon: '🌑',
        lightBackground: '#EFEFEF',
        darkBackground: '#0D0D0D',
        soundType: 'silence',
        soundVolume: 0,
        lineHeightShift: 0.15,
        letterSpacingShift: 0.03,
        isPreset: true,
        projectId: null,
        createdAt: new Date('2026-01-01')
    },
    {
        id: 'preset-battle',
        name: 'Battle',
        icon: '🔥',
        lightBackground: '#F5EDE8',
        darkBackground: '#140800',
        soundType: 'energetic-loop',
        soundVolume: 0.45,
        lineHeightShift: -0.1,
        letterSpacingShift: 0,
        isPreset: true,
        projectId: null,
        createdAt: new Date('2026-01-01')
    },
    {
        id: 'preset-wonder',
        name: 'Wonder',
        icon: '🌌',
        lightBackground: '#EEEAF5',
        darkBackground: '#0A0814',
        soundType: 'dark-ambient',
        soundVolume: 0.3,
        lineHeightShift: 0.1,
        letterSpacingShift: 0.02,
        isPreset: true,
        projectId: null,
        createdAt: new Date('2026-01-01')
    },
    {
        id: 'preset-focus',
        name: 'Focus',
        icon: '🎯',
        lightBackground: '#F0F0F0',
        darkBackground: '#101010',
        soundType: 'pink-noise',
        soundVolume: 0.3,
        lineHeightShift: 0,
        letterSpacingShift: 0,
        isPreset: true,
        projectId: null,
        createdAt: new Date('2026-01-01')
    }
];
