/**
 * Export Utility Library
 * 
 * Provides pure functions to serialize MythForge internal data structures 
 * (Documents and Entities) into standard, portable file formats (Markdown, DOCX).
 * Handles the browser Blob bridging to trigger direct file downloads natively.
 */

import { Document as MFDocument, Entity, Scene } from '@/store/workspaceStore';
import { Document as DocxDocument, Paragraph, TextRun, Packer } from 'docx';

/**
 * Strips HTML artifacts generated by Tiptap/ProseMirror back into 
 * standard, readable Markdown.
 */
function htmlToMarkdown(htmlText: string): string {
    let md = htmlText;

    // Convert paragraph blocks into double newlines for spacing
    md = md.replace(/<\/p>\s*<p>/g, '\n\n');
    md = md.replace(/<p>/g, '');
    md = md.replace(/<\/p>/g, '');

    // Convert bold weights
    md = md.replace(/<strong>(.*?)<\/strong>/g, '**$1**');
    md = md.replace(/<b>(.*?)<\/b>/g, '**$1**');

    // Convert italics
    md = md.replace(/<em>(.*?)<\/em>/g, '*$1*');
    md = md.replace(/<i>(.*?)<\/i>/g, '*$1*');

    // Convert breaks
    md = md.replace(/<br\s*\/?>/g, '\n');

    // Strip entity marking spans but preserve their inner textual name completely
    md = md.replace(/<span[^>]*class="[^"]*entity-tag[^"]*"[^>]*>(.*?)<\/span>/g, '$1');

    // Fallback terminator: Strip ANY remaining HTML tags blindly
    md = md.replace(/<[^>]*>?/gm, '');

    return md;
}

/**
 * Triggers a browser file download using a transient Blob URL.
 */
function downloadFile(content: BlobPart, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

/**
 * Sanitizes strings for safe file naming logic (lowercase, hyphens, alphanumeric).
 */
function slugify(text: string): string {
    return text
        .toString()
        .toLowerCase()
        .replace(/\s+/g, '-')       // Replace spaces with -
        .replace(/[^\w-]+/g, '')    // Remove all non-word chars
        .replace(/--+/g, '-')       // Replace multiple - with single -
        .replace(/^-+/, '')         // Trim - from start of text
        .replace(/-+$/, '');        // Trim - from end of text
}

/**
 * Exports a single Document as a .md file.
 * 
 * @param {MFDocument} document - The MythForge document to serialize.
 * @param {string} projectName - The name of the project context, usually unused in markdown but required for standard signature.
 */
export function exportAsMarkdown(document: MFDocument, scenes: Scene[]): void {
    const title = document.title || 'Untitled Document';
    let finalMarkdown = `# ${title}\n\n`;

    const orderedScenes = [...scenes].sort((a, b) => a.order - b.order);

    orderedScenes.forEach((scene) => {
        finalMarkdown += `## ${scene.title}\n\n`;
        finalMarkdown += `${htmlToMarkdown(scene.content)}\n\n`;
    });

    downloadFile(finalMarkdown, `${slugify(title)}.md`, 'text/markdown');
}

/**
 * Exports a single Document as a rich .docx file formatted to standard manuscript requirements.
 * 
 * @param {MFDocument} document - The MythForge document to serialize.
 * @param {string} projectName - The name of the project context.
 * @returns {Promise<void>} 
 */
export async function exportAsDocx(document: MFDocument, scenes: Scene[]): Promise<void> {
    const title = document.title || 'Untitled Document';
    const parser = new DOMParser();

    const docxParagraphs: Paragraph[] = [
        new Paragraph({
            text: title,
            heading: "Heading1",
            spacing: { after: 400 }, // Creates breathing room after title
        })
    ];

    const orderedScenes = [...scenes].sort((a, b) => a.order - b.order);

    orderedScenes.forEach((scene) => {
        docxParagraphs.push(new Paragraph({
            text: scene.title,
            heading: "Heading2"
        }));

        const doc = parser.parseFromString(scene.content, 'text/html');
        const pElements = Array.from(doc.querySelectorAll('p'));

        pElements.forEach(pNode => {
            // If it's an empty line breaker
            if (!pNode.textContent?.trim()) {
                docxParagraphs.push(new Paragraph({ text: "" }));
                return;
            }

            const runs: TextRun[] = [];
            pNode.childNodes.forEach(child => {
                if (child.nodeType === Node.TEXT_NODE) {
                    if (child.textContent) {
                        runs.push(new TextRun({ text: child.textContent }));
                    }
                } else if (child.nodeType === Node.ELEMENT_NODE) {
                    const element = child as HTMLElement;
                    const textContent = element.textContent || '';

                    // Track style derivations
                    const isBold = element.tagName === 'STRONG' || element.tagName === 'B';
                    const isItalic = element.tagName === 'EM' || element.tagName === 'I';

                    // Entity spans inherently lack visual decorators on export, they just become plain text.
                    runs.push(new TextRun({
                        text: textContent,
                        bold: isBold,
                        italics: isItalic
                    }));
                }
            });

            docxParagraphs.push(new Paragraph({
                children: runs,
            }));
        });
    });

    const docxApp = new DocxDocument({
        sections: [
            {
                properties: {
                    page: {
                        margin: {
                            top: 1440,    // 1 inch = 1440 twips
                            right: 1440,
                            bottom: 1440,
                            left: 1440,
                        },
                    },
                },
                children: docxParagraphs,
            },
        ],
        styles: {
            default: {
                document: {
                    run: {
                        font: "Times New Roman",
                        size: 24, // 12pt (value is half-points)
                    },
                    paragraph: {
                        spacing: {
                            line: 360, // 1.5 line spacing (240 is single)
                            before: 120,
                            after: 120,
                        },
                    }
                },
                heading1: {
                    run: {
                        font: "Times New Roman",
                        size: 48, // 24pt
                        bold: true,
                        color: "000000"
                    }
                },
                heading2: {
                    run: {
                        font: "Times New Roman",
                        size: 32, // 16pt
                        bold: true,
                        color: "000000"
                    },
                    paragraph: {
                        spacing: {
                            before: 240,
                            after: 120
                        }
                    }
                }
            }
        }
    });

    const blob = await Packer.toBlob(docxApp);
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement('a');
    a.href = url;
    a.download = `${slugify(title)}.docx`;
    window.document.body.appendChild(a);
    a.click();
    window.document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

/**
 * Aggregates all world entities within a project into a single Markdown encyclopedia.
 * 
 * @param {Entity[]} entities - The list of entities belonging to the active project constraints.
 * @param {string} projectName - Used for dynamic title generation.
 */
export function exportWorldBible(entities: Entity[], projectName: string): void {
    const safeProjectName = projectName || 'MythForge Project';
    let output = `# ${safeProjectName} — World Bible\n\n`;

    const typeOrder = ['character', 'location', 'faction', 'artifact', 'lore'];

    // Sort logic mapping internal enum keys to human-readable headers
    const entityTypeLabels: Record<string, string> = {
        'character': 'Characters',
        'location': 'Locations',
        'faction': 'Factions',
        'artifact': 'Artifacts',
        'lore': 'Lore & History'
    };

    typeOrder.forEach(typeKey => {
        const matchingEntities = entities.filter(e => e.type === typeKey);
        if (matchingEntities.length > 0) {
            output += `## ${entityTypeLabels[typeKey]}\n\n`;

            // Map individual entries
            matchingEntities.forEach(entity => {
                output += `### ${entity.name}\n`;
                // Single uppercase the first char of type for visual display
                const visualType = typeKey.charAt(0).toUpperCase() + typeKey.slice(1);
                output += `**Type:** ${visualType}\n\n`;
                output += `${entity.description}\n\n`;
            });
        }
    });

    downloadFile(output, `${slugify(safeProjectName)}-world-bible.md`, 'text/markdown');
}
