/**
 * The Ren'Py assembler for the season timeline. LEAF MODULE, and pure: data
 * in, string out.
 *
 * Nothing here can be verified by running it — this machine has no Ren'Py SDK
 * — so the tests are the only safety net.
 *
 * The rule that shapes everything: Ren'Py continues past a menu once an
 * option's block finishes. So "rejoin within the episode" is the language's
 * own default and emits no jump at all. The only jumps written are a
 * cross-episode route, and the implicit hand-off to the next episode.
 */

import {
    toIdentifier, escapeRenpyText, buildAliasMap, buildFlagNameMap,
} from './renpyExport';
import { formatDefault, formatEffect, formatCondition, type VNFlag } from './vnFlags';
import type { VNSeason, VNEpisode } from './vnTimeline';

const INDENT = '    ';

/** Episodes in play order: by season order, then by episode order. */
function inPlayOrder(seasons: VNSeason[], episodes: VNEpisode[]): VNEpisode[] {
    const rank = new Map(
        [...seasons].sort((a, b) => a.order - b.order).map((s, i) => [s.id, i]),
    );
    return [...episodes].sort((a, b) => {
        const sa = rank.get(a.seasonId ?? '') ?? Number.MAX_SAFE_INTEGER;
        const sb = rank.get(b.seasonId ?? '') ?? Number.MAX_SAFE_INTEGER;
        return sa - sb || a.order - b.order;
    });
}

/**
 * Episode id → label, as `s1e2_the_bar`. Season and episode numbers come from
 * play order rather than from any stored index, so inserting an episode
 * renumbers the ones after it exactly as a reader would expect.
 */
export function episodeLabels(
    seasons: VNSeason[],
    episodes: VNEpisode[],
): Map<string, string> {
    const seasonNumber = new Map(
        [...seasons].sort((a, b) => a.order - b.order).map((s, i) => [s.id, i + 1]),
    );

    const counters = new Map<string, number>();
    const taken = new Set<string>();
    const labels = new Map<string, string>();

    for (const episode of inPlayOrder(seasons, episodes)) {
        const sKey = episode.seasonId ?? '';
        const sNum = seasonNumber.get(sKey) ?? 0;
        const eNum = (counters.get(sKey) ?? 0) + 1;
        counters.set(sKey, eNum);

        const slug = toIdentifier(episode.title, 'untitled', '_episode');
        const base = `s${sNum}e${eNum}_${slug}`;

        let label = base;
        let n = 2;
        while (taken.has(label)) {
            label = `${base}_${n}`;
            n += 1;
        }

        taken.add(label);
        labels.set(episode.id, label);
    }

    return labels;
}

/** Speakers needing a `define`, from the cast plus any name used in prose. */
function collectSpeakers(castNames: string[]): string[] {
    const names: string[] = [];
    const seen = new Set<string>();
    for (const name of castNames) {
        const key = name.toLowerCase();
        if (seen.has(key)) continue;
        seen.add(key);
        names.push(name);
    }
    return names;
}

/**
 * The whole .rpy file for a season timeline.
 *
 * `castNames` seeds the character definitions. Scene prose is not yet part of
 * the timeline model — the Writing Desk owns it — so this emits structure and
 * state, which is what a draft is for.
 */
export function buildTimelineScript(
    seasons: VNSeason[],
    episodes: VNEpisode[],
    castNames: string[],
    projectName: string,
    flags: VNFlag[] = [],
): string {
    const ordered = inPlayOrder(seasons, episodes);
    const labels = episodeLabels(seasons, episodes);

    const speakers = collectSpeakers(castNames);
    const aliases = buildAliasMap(speakers);

    const flagNames = buildFlagNameMap(flags);

    const out: string[] = [
        `# Generated by LoreCanvas — ${projectName}`,
        `# Drop this file into your Ren'Py project's game/ folder.`,
        '',
    ];

    for (const name of speakers) {
        out.push(`define ${aliases.get(name)} = Character("${escapeRenpyText(name)}")`);
    }
    if (speakers.length) out.push('');

    for (const flag of [...flags].sort((a, b) => a.name.localeCompare(b.name))) {
        out.push(formatDefault(flag, flagNames.get(flag.id)!));
    }
    if (flags.length) out.push('');

    if (!ordered.length) return `${out.join('\n').trimEnd()}\n`;

    out.push('label start:', `${INDENT}jump ${labels.get(ordered[0].id)}`, '');

    ordered.forEach((episode, index) => {
        out.push(`label ${labels.get(episode.id)}:`);

        const decisions = [...(episode.decisions ?? [])]
            .sort((a, b) => a.order - b.order)
            .filter(d => d.options.length);

        for (const decision of decisions) {
            out.push(`${INDENT}menu:`);

            for (const option of decision.options) {
                const identifier = option.condition
                    ? flagNames.get(option.condition.flagId)
                    : undefined;
                const guard = option.condition && identifier
                    ? ` if ${formatCondition(option.condition, identifier)}`
                    : '';
                out.push(`${INDENT.repeat(2)}"${escapeRenpyText(option.text)}"${guard}:`);

                const body: string[] = [];
                for (const effect of option.effects ?? []) {
                    const name = flagNames.get(effect.flagId);
                    // A flag deleted from the registry leaves dangling effects.
                    // Skipping beats emitting `$ undefined = True`.
                    if (!name) continue;
                    body.push(formatEffect(effect, name));
                }

                // Only a route writes a jump. Everything else rejoins, which
                // Ren'Py does on its own once the block ends.
                const target = option.routeToEpisodeId
                    ? labels.get(option.routeToEpisodeId)
                    : undefined;
                if (target) body.push(`jump ${target}`);

                // A menu option's block cannot be empty.
                if (!body.length) body.push('pass');

                for (const line of body) out.push(`${INDENT.repeat(3)}${line}`);
                out.push('');
            }
        }

        const next = ordered[index + 1];
        out.push(next ? `${INDENT}jump ${labels.get(next.id)}` : `${INDENT}return`);
        out.push('');
    });

    return `${out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}
