import { WritingMethod } from '../types';

/**
 * Mythic / character-arc journeys and character/world-first methods.
 * Field-guide families III (mythic) and VIII (character-first / worldbuilding-first).
 */
export const CHARACTER_METHODS: WritingMethod[] = [
    {
        id: 'heros-journey',
        name: "Hero's Journey",
        family: 'mythic',
        formats: ['story', 'script', 'game'],
        tagline: 'Twelve stages of departure, initiation, and return — the monomyth.',
        bestFor: 'Fantasy, adventure, transformation stories',
        beats: [
            { group: 'Departure', label: 'Ordinary World', guidance: 'The hero at home, before the adventure. Establish what they\'ll leave behind and what\'s missing from their life.', placeholder: 'e.g. A farm boy stares at twin sunsets, going nowhere…' },
            { group: 'Departure', label: 'Call to Adventure', guidance: 'The invitation — a challenge, discovery, or plea that beckons the hero out of the ordinary.', placeholder: 'e.g. A hidden message: "Help me, you\'re my only hope."' },
            { group: 'Departure', label: 'Refusal of the Call', guidance: 'The hero hesitates or refuses. Fear, duty, or doubt hold them in place — showing the cost of leaving.', placeholder: 'e.g. "I\'ve got work to do. It\'s not that I like the Empire…"' },
            { group: 'Departure', label: 'Meeting the Mentor', guidance: 'A guide provides wisdom, tools, or confidence the hero will need.', placeholder: 'e.g. The old hermit gifts the father\'s sword…' },
            { group: 'Departure', label: 'Crossing the Threshold', guidance: 'The hero commits and enters the special world. The rules change; there\'s no easy way back.', placeholder: 'e.g. The cantina, the smuggler, the leap to lightspeed…' },
            { group: 'Initiation', label: 'Tests, Allies, Enemies', guidance: 'The hero learns the new world\'s rules through trials, gaining friends and foes.', placeholder: 'e.g. Chess with a wookiee; a first clumsy duel…' },
            { group: 'Initiation', label: 'Approach the Inmost Cave', guidance: 'Preparation for the central ordeal. Tension gathers as the hero nears the most dangerous place.', placeholder: 'e.g. Drawn by tractor beam into the battle station…' },
            { group: 'Initiation', label: 'The Ordeal', guidance: 'Death and rebirth — the hero faces their greatest fear and is transformed by surviving it.', placeholder: 'e.g. The walls close in; the mentor falls…' },
            { group: 'Initiation', label: 'Reward', guidance: 'The hero seizes what they came for — an object, knowledge, or reconciliation — but the danger isn\'t over.', placeholder: 'e.g. The princess rescued, the plans in hand…' },
            { group: 'Return', label: 'The Road Back', guidance: 'The chase home. The special world doesn\'t let go easily; the stakes turn personal.', placeholder: 'e.g. Fighters pursue the escaping ship…' },
            { group: 'Return', label: 'Resurrection', guidance: 'The final, hardest test — the hero must prove the transformation is real, alone.', placeholder: 'e.g. The trench run: switch off the targeting computer…' },
            { group: 'Return', label: 'Return with the Elixir', guidance: 'The hero comes home changed, carrying something that heals the ordinary world.', placeholder: 'e.g. Medals, and a farm boy who is no longer one…' },
        ],
    },
    {
        id: 'story-circle',
        name: 'Story Circle',
        family: 'mythic',
        formats: ['story', 'script'],
        tagline: 'Eight steps around a circle: leave comfort, pay a price, return changed.',
        bestFor: 'Episodic TV, character-driven stories, short fiction',
        starter: true,
        beats: [
            { label: '1. You', guidance: 'A character in their zone of comfort. Establish who we\'re following and their familiar order.', placeholder: 'e.g. A barista who has memorized every regular\'s order…' },
            { label: '2. Need', guidance: 'But they want something. Name the desire — conscious or not — that will pull them out.', placeholder: 'e.g. …and keeps an unmailed art-school application under the register.' },
            { label: '3. Go', guidance: 'They enter an unfamiliar situation. Cross the threshold into chaos — the world where the old rules fail.', placeholder: 'e.g. The café closes overnight; she takes a job painting sets…' },
            { label: '4. Search', guidance: 'Adapt to the new world. Trial, error, and the road of trials — competence earned the hard way.', placeholder: 'e.g. She ruins two backdrops before the designer shows her the trick…' },
            { label: '5. Find', guidance: 'They get what they wanted. The goal is reached — but it\'s rarely what they expected.', placeholder: 'e.g. Her design gets picked for the main stage…' },
            { label: '6. Take', guidance: 'Pay a heavy price for it. Getting the want costs something real — this is where the lesson lives.', placeholder: 'e.g. …the night of her best friend\'s wedding.' },
            { label: '7. Return', guidance: 'Return to the familiar situation. Come back to where they started, carrying what happened.', placeholder: 'e.g. Back behind the counter, paint still under her nails…' },
            { label: '8. Change', guidance: 'Having changed. Show the difference — the same world, met by a different person.', placeholder: 'e.g. The application is in the mail; the register drawer is lighter…' },
        ],
    },
    {
        id: 'truby-22-steps',
        name: "Truby's 22 Steps",
        family: 'mythic',
        formats: ['story', 'script'],
        tagline: 'Twenty-two interlocking steps built around a moral argument and a character web.',
        bestFor: 'Literary fiction, complex antagonists, morally serious stories',
        beats: [
            { group: 'Foundation', label: 'Self-Revelation, Need & Desire', guidance: 'Design the ending first: what will the hero learn about themselves? Work backward from that revelation.', placeholder: 'e.g. He will learn that loyalty bought with silence is complicity…' },
            { group: 'Foundation', label: 'Ghost & Story World', guidance: 'The wound from the past that haunts the hero, and the world that mirrors their inner state.', placeholder: 'e.g. The brother he didn\'t testify for; a city of sealed records…' },
            { group: 'Foundation', label: 'Weakness & Need', guidance: 'The psychological flaw hurting the hero, and the moral flaw hurting others.', placeholder: 'e.g. Psychological: avoids conflict / Moral: lets the weak pay for it…' },
            { group: 'Foundation', label: 'Inciting Event', guidance: 'The event from outside that forces the hero out of paralysis.', placeholder: 'e.g. A clerk hands him the wrong file — his brother\'s…' },
            { group: 'Foundation', label: 'Desire', guidance: 'The specific goal the hero forms. The story\'s spine — concrete and visible.', placeholder: 'e.g. Reopen the case before the archive is destroyed…' },
            { group: 'The Web', label: 'Ally or Allies', guidance: 'Companions who help — each one an angle on the story\'s moral question.', placeholder: 'e.g. An archivist who saves everything and risks nothing…' },
            { group: 'The Web', label: 'Opponent', guidance: 'Not a villain — the person best positioned to attack the hero\'s weakness, who wants the same thing.', placeholder: 'e.g. The judge who sealed the records — to protect his own son…' },
            { group: 'The Web', label: 'Fake-Ally Opponent', guidance: 'An apparent friend secretly working against the hero. The web\'s most interesting node.', placeholder: 'e.g. The journalist feeding his leads to the judge…' },
            { group: 'The Web', label: 'First Revelation & Decision', guidance: 'New information changes the hero\'s understanding; they adjust course and commit harder.', placeholder: 'e.g. The file was mis-shelved on purpose — someone wanted it found…' },
            { group: 'Escalation', label: 'Plan', guidance: 'The hero\'s strategy to reach the goal. It will fail — that\'s the point.', placeholder: 'e.g. Copy everything quietly, then file one loud motion…' },
            { group: 'Escalation', label: "Opponent's Plan", guidance: 'The opponent\'s counter-strategy — hidden, smarter, already in motion.', placeholder: 'e.g. Let him dig; the deeper the file, the older the crime it implicates…' },
            { group: 'Escalation', label: 'Drive', guidance: 'The campaign: actions, reversals, and the hero starting to bend their own morals to win.', placeholder: 'e.g. He forges a signature to get one door open…' },
            { group: 'Escalation', label: 'Attack by Ally', guidance: 'The conscience moment — an ally confronts the hero about what they\'re becoming.', placeholder: 'e.g. "You\'re sealing records of your own now."' },
            { group: 'Escalation', label: 'Apparent Defeat', guidance: 'The hero\'s lowest point. The goal looks impossible; the weakness has won.', placeholder: 'e.g. The archive burns; the journalist prints his forgery…' },
            { group: 'Escalation', label: 'Second Revelation & Decision', guidance: 'A deeper truth revives the hero with clearer eyes and a changed plan.', placeholder: 'e.g. His brother knew. He pleaded guilty to protect someone…' },
            { group: 'Escalation', label: 'Audience Revelation', guidance: 'The reader learns something the hero doesn\'t know yet — usually the fake-ally\'s truth.', placeholder: 'e.g. We see the journalist\'s desk: a photo of the judge\'s son…' },
            { group: 'Escalation', label: 'Third Revelation & Decision', guidance: 'The hero finally sees the whole board — including the fake-ally\'s betrayal.', placeholder: 'e.g. The byline history was in the file all along…' },
            { group: 'Endgame', label: 'Gate, Gauntlet, Visit to Death', guidance: 'The narrowing corridor: pressure peaks and the hero brushes mortality — literal or symbolic.', placeholder: 'e.g. The night in the flooded records basement…' },
            { group: 'Endgame', label: 'Battle', guidance: 'The final conflict — the moral argument made physical. Both sides\' values collide openly.', placeholder: 'e.g. He testifies — against the judge, and against his own silence…' },
            { group: 'Endgame', label: 'Self-Revelation', guidance: 'The hero sees themselves truly, psychologically and morally. The moment the whole design aims at.', placeholder: 'e.g. Silence was never neutral. He names his own part first…' },
            { group: 'Endgame', label: 'Moral Decision', guidance: 'The hero proves the revelation with an action that costs them something.', placeholder: 'e.g. He surrenders the forged motion — voiding his own case…' },
            { group: 'Endgame', label: 'New Equilibrium', guidance: 'The world settles at a new level. The hero — and the web around them — stand rearranged.', placeholder: 'e.g. The archive reopens, one honest clerk at the desk…' },
        ],
    },
    {
        id: 'virgins-promise',
        name: "The Virgin's Promise",
        family: 'mythic',
        formats: ['story', 'script'],
        tagline: 'Thirteen beats of coming into your own power — the inward mirror of the Hero\'s Journey.',
        bestFor: 'Coming-into-power arcs, self-actualization, strong secondary arcs',
        beats: [
            { label: 'Dependent World', guidance: 'The protagonist lives by others\' expectations. Show the community whose approval they depend on.', placeholder: 'e.g. Eldest daughter of the inn; everyone\'s schedule but her own…' },
            { label: 'Price of Conformity', guidance: 'What staying small costs them. The dream deferred, the self suppressed.', placeholder: 'e.g. Her sheet music yellows in the cellar…' },
            { label: 'Opportunity to Shine', guidance: 'A chance appears to secretly express the true self.', placeholder: 'e.g. The tavern piano sits unattended between shifts…' },
            { label: 'Dresses the Part', guidance: 'They step into the authentic self — often literally in new clothes or a new persona.', placeholder: 'e.g. She plays as "the Marek boy" behind a drawn curtain…' },
            { label: 'The Secret World', guidance: 'A double life begins: conforming by day, becoming themselves in hidden moments.', placeholder: 'e.g. Innkeeper\'s daughter by day, the curtained pianist by night…' },
            { label: 'No Longer Fits Her World', guidance: 'The true self grows too big to hide. Slips, close calls, growing dissonance.', placeholder: 'e.g. She hums her nocturne while serving the magistrate…' },
            { label: 'Caught Shining', guidance: 'The secret is exposed. The dependent world sees the true self — and reacts.', placeholder: 'e.g. The curtain falls mid-sonata; her father in the doorway…' },
            { label: 'Gives Up What Kept Her Stuck', guidance: 'The protagonist stops managing everyone else\'s comfort and claims their own path.', placeholder: 'e.g. She hands the ledger back: "The inn was never mine."' },
            { label: 'Kingdom in Chaos', guidance: 'The community reels. The old order wobbles because one person changed.', placeholder: 'e.g. The inn falters; the sisters quarrel over who fills the gap…' },
            { label: 'Wanders in the Wilderness', guidance: 'Alone between worlds — the old self gone, the new one not yet secure.', placeholder: 'e.g. Conservatory auditions in a city where nobody owes her kindness…' },
            { label: 'Chooses Her Light', guidance: 'The decisive commitment to the true self, publicly, whatever it costs.', placeholder: 'e.g. She plays her own composition, under her own name…' },
            { label: 'Re-ordering', guidance: 'The community reorganizes around the new truth — often with a rescue that flows both ways.', placeholder: 'e.g. Her father books the tavern\'s first concert night…' },
            { label: 'The Kingdom Is Brighter', guidance: 'The world is better because the protagonist shone. Their light lifts everyone.', placeholder: 'e.g. Three village girls now take Sunday lessons at the inn piano…' },
        ],
    },
    {
        id: 'hauge-six-stage',
        name: "Hauge's Six-Stage Structure",
        family: 'mythic',
        formats: ['story', 'script'],
        tagline: 'Six stages and five turning points tracking the journey from identity to essence.',
        bestFor: 'Character-focused stories and screenplays',
        beats: [
            { label: 'Stage 1: Setup', guidance: 'The hero living fully inside their identity — the protective persona built around an old wound. Ends at Turning Point 1: the Opportunity (~10%).', placeholder: 'e.g. The fixer who believes everyone is buyable, fixing another scandal…' },
            { label: 'Stage 2: New Situation', guidance: 'The opportunity carries the hero into new circumstances. They react, adjust, and glimpse what living from essence might feel like. Ends at TP2: the Change of Plans (~25%).', placeholder: 'e.g. Assigned to bury a story about the one person who can\'t be bought…' },
            { label: 'Stage 3: Progress', guidance: 'The plan works — visible progress toward the outer goal, while the inner conflict simmers. Ends at TP3: the Point of No Return (~50%).', placeholder: 'e.g. Every angle works; and he starts feeding her tips anonymously…' },
            { label: 'Stage 4: Complications & Higher Stakes', guidance: 'Past the point of no return, everything gets harder. Identity and essence pull in opposite directions. Ends at TP4: the Major Setback (~75%).', placeholder: 'e.g. His employer discovers the leaks; she discovers his name…' },
            { label: 'Stage 5: Final Push', guidance: 'All in. The hero risks everything, living almost fully from essence. Ends at TP5: the Climax (~90–99%).', placeholder: 'e.g. He goes on record — his own scandals first…' },
            { label: 'Stage 6: Aftermath', guidance: 'The new life. Show the hero transformed — or show the price of retreating into identity.', placeholder: 'e.g. Smaller office, honest work, his name on the byline…' },
        ],
    },

    // ── Character-first / Worldbuilding-first ────────────────
    {
        id: 'character-first',
        name: 'Character-First Development',
        family: 'first-principles',
        formats: ['story', 'script'],
        tagline: 'Start with wound, want, and need — and let the plot grow out of the person.',
        bestFor: 'Character-driven fiction where plot serves inner change',
        beats: [
            { label: 'The Wound', guidance: 'The past injury that shaped this person. It happened before the story; the story happens because of it.', placeholder: 'e.g. Her testimony freed the wrong man…' },
            { label: 'The Lie They Believe', guidance: 'The false lesson drawn from the wound — the belief that protects and imprisons them.', placeholder: 'e.g. "Certainty is a luxury other people can afford."' },
            { label: 'The Want', guidance: 'The conscious external goal they\'d name if asked. Concrete, visible, pursuable.', placeholder: 'e.g. Close one last case and retire clean…' },
            { label: 'The Need', guidance: 'What would actually heal them — usually the opposite of the lie. They can\'t see it yet.', placeholder: 'e.g. To trust her own judgment again…' },
            { label: 'The Flaw in Action', guidance: 'How the lie shows up as behavior that damages them and others. This generates your scenes.', placeholder: 'e.g. Triple-checks everything; misses what\'s in front of her…' },
            { label: 'Scenes This Character Demands', guidance: 'List the scenes the arc requires: a scene that shows the flaw, one that stresses the lie, one that offers the truth, one that forces the choice.', placeholder: 'e.g. Flaw scene… / Stress scene… / Truth glimpse… / Final choice…' },
        ],
    },
    {
        id: 'worldbuilding-first',
        name: 'Worldbuilding-First',
        family: 'first-principles',
        formats: ['story', 'game'],
        tagline: 'Build the world\'s rules first — then find the story they make inevitable.',
        bestFor: 'SFF and lore-heavy fiction (with a guard against worldbuilder\'s disease)',
        beats: [
            { label: 'The Premise', guidance: 'The one big difference between this world and ours. Everything else derives from it.', placeholder: 'e.g. The dead linger for one year as advisors…' },
            { label: 'Rules & Systems', guidance: 'How the premise works: limits, costs, and edge cases. Constraints create stories; powers alone don\'t.', placeholder: 'e.g. The dead can\'t lie — but they can stay silent…' },
            { label: 'Cultures & Institutions', guidance: 'How societies organized around the rules. Who benefits, who\'s excluded, what\'s taboo.', placeholder: 'e.g. Inheritance courts where the deceased testifies…' },
            { label: 'Conflict Seeds', guidance: 'Where the system creates unavoidable friction — each seed is a story waiting to sprout.', placeholder: 'e.g. What happens to the murdered, whose year runs out mid-trial?…' },
            { label: 'The Story This World Demands', guidance: 'Pick the character the premise hurts most and give them the want the rules forbid. That\'s your novel.', placeholder: 'e.g. A widow who must prosecute her husband\'s ghost…' },
            { label: 'The 10% Budget', guidance: 'Sanderson\'s rule: worldbuilding notes should stay near 10% of your story\'s word count. If lore outgrows that, write story, not setting.', placeholder: 'e.g. Target: 100k novel → keep these notes near 10k words.' },
        ],
    },
];
