import { WritingMethod } from '../types';

/**
 * Classic structures, beat sheets, and expansion (fractal) methods.
 * Field-guide families I (fractal), II (beat-sheet), V (classical).
 */
export const STRUCTURE_METHODS: WritingMethod[] = [
    // ── Classical ────────────────────────────────────────────
    {
        id: 'three-act',
        name: 'Three-Act Structure',
        family: 'classical',
        formats: ['story', 'script'],
        tagline: 'Setup, confrontation, resolution — the universal default.',
        bestFor: 'Any story; the structure most others are built on',
        starter: true,
        beats: [
            { group: 'Act I', label: 'Setup', guidance: 'Introduce your protagonist in their normal world. Show what they want and what their life looks like before everything changes.', placeholder: 'e.g. Mara repairs clocks in a city where time is currency…' },
            { group: 'Act I', label: 'Inciting Incident', guidance: 'The event that disrupts the normal world and sets the story in motion. It happens TO the protagonist.', placeholder: 'e.g. A customer brings in a clock that runs backwards…' },
            { group: 'Act I', label: 'Plot Point One', guidance: 'The protagonist makes a choice they can\'t take back. This decision launches them into Act II.', placeholder: 'e.g. Mara steals the clock and flees the city…' },
            { group: 'Act II', label: 'Rising Action', guidance: 'Obstacles escalate. The protagonist tries and fails, learning what this journey really costs.', placeholder: 'e.g. Every fence refuses to buy it; the Timekeepers close in…' },
            { group: 'Act II', label: 'Midpoint', guidance: 'A major shift — a false victory or false defeat that changes the protagonist\'s goal or approach.', placeholder: 'e.g. Mara discovers the clock doesn\'t reverse time — it stores it…' },
            { group: 'Act II', label: 'Plot Point Two', guidance: 'The lowest moment. Everything falls apart, and the old way of doing things is dead.', placeholder: 'e.g. Her brother is arrested with the years she saved for him…' },
            { group: 'Act III', label: 'Climax', guidance: 'The final confrontation. The protagonist faces the central conflict head-on, changed by the journey.', placeholder: 'e.g. Mara opens the clock inside the Central Exchange…' },
            { group: 'Act III', label: 'Resolution', guidance: 'The aftermath. Show the new normal and what the journey cost or earned.', placeholder: 'e.g. Time is free; Mara\'s shop repairs anything but clocks…' },
        ],
    },
    {
        id: 'freytag-pyramid',
        name: "Freytag's Pyramid",
        family: 'classical',
        formats: ['story', 'script'],
        tagline: 'Rise to a central climax, then fall to consequence — the shape of tragedy.',
        bestFor: 'Tragedy and stories where the aftermath matters as much as the peak',
        beats: [
            { label: 'Exposition', guidance: 'Establish the world, characters, and the seed of the coming conflict.', placeholder: 'e.g. Two houses, alike in dignity…' },
            { label: 'Rising Action', guidance: 'Complications stack. Each event tightens the knot and raises what\'s at stake.', placeholder: 'e.g. The secret marriage, the street duel…' },
            { label: 'Climax', guidance: 'The turning point at the story\'s center — the moment of highest tension where fortunes reverse.', placeholder: 'e.g. Tybalt falls; banishment…' },
            { label: 'Falling Action', guidance: 'Consequences unspool. The reversal plays out; events accelerate toward the end.', placeholder: 'e.g. The desperate plan, the letter that never arrives…' },
            { label: 'Denouement', guidance: 'The final outcome and what it means. In tragedy, the catastrophe; elsewhere, the settling of dust.', placeholder: 'e.g. A glooming peace this morning with it brings…' },
        ],
    },
    {
        id: 'fichtean-curve',
        name: 'Fichtean Curve',
        family: 'classical',
        formats: ['story'],
        tagline: 'Skip the setup — open in crisis and stack escalating crises to the climax.',
        bestFor: 'Thrillers, page-turners, stories that can\'t afford a slow start',
        beats: [
            { label: 'Opening Crisis', guidance: 'Start inside a problem. Exposition gets smuggled in while the reader is already gripped.', placeholder: 'e.g. The car won\'t start and the tide is coming in…' },
            { label: 'Crisis Two', guidance: 'A bigger problem than the first. Each crisis should be objectively worse than the last.', placeholder: 'e.g. The phone is dead — and someone moved the keys…' },
            { label: 'Crisis Three', guidance: 'Escalate again. Give a short breather after the last crisis, then hit harder.', placeholder: 'e.g. The footprints in the sand aren\'t hers…' },
            { label: 'Crisis Four', guidance: 'The screws tighten to near-breaking. The protagonist\'s options are almost gone.', placeholder: 'e.g. The water reaches the dunes; the stranger waves…' },
            { label: 'Climax', guidance: 'The biggest crisis of all — the confrontation everything has been building toward.', placeholder: 'e.g. She recognizes him from the missing-person poster…' },
            { label: 'Brief Resolution', guidance: 'Keep it short. A quick landing after the peak — the Fichtean curve barely touches the ground.', placeholder: 'e.g. Dawn. Sirens. Her name being called…' },
        ],
    },
    {
        id: 'kishotenketsu',
        name: 'Kishōtenketsu',
        family: 'classical',
        formats: ['story', 'article'],
        tagline: 'A four-part structure built on a twist of perspective, not conflict.',
        bestFor: 'Literary fiction, slice-of-life, stories that don\'t need an antagonist',
        beats: [
            { label: 'Ki — Introduction', guidance: 'Introduce the characters and situation. No conflict required — just presence and place.', placeholder: 'e.g. A grandmother tends her vegetable stall each morning…' },
            { label: 'Shō — Development', guidance: 'Deepen what was introduced. Let the reader settle into the world and its rhythms.', placeholder: 'e.g. The same customers, the same jokes, the seasons turning…' },
            { label: 'Ten — Twist', guidance: 'The turn: something unexpected recontextualizes everything — a new perspective, not a battle.', placeholder: 'e.g. A city inspector arrives with a photograph of the stall from 1954…' },
            { label: 'Ketsu — Conclusion', guidance: 'Reconcile the twist with what came before. The pieces settle into a new, richer whole.', placeholder: 'e.g. She hangs the photograph where the price board was…' },
        ],
    },

    // ── Beat sheets ──────────────────────────────────────────
    {
        id: 'save-the-cat',
        name: 'Save the Cat',
        family: 'beat-sheet',
        formats: ['story', 'script'],
        tagline: 'Fifteen beats anchored to page-count percentages — the commercial standard.',
        bestFor: 'Commercial and genre fiction, screenplays',
        starter: true,
        beats: [
            { group: 'Act I', label: 'Opening Image', guidance: 'A snapshot of the hero\'s life before the story — the "before" photo the Final Image will mirror.', placeholder: 'e.g. Alone at a vending-machine dinner, again…' },
            { group: 'Act I', label: 'Theme Stated', guidance: 'Someone states what the story is really about — usually to a hero who isn\'t ready to hear it.', placeholder: 'e.g. "You can\'t outrun people forever, you know."' },
            { group: 'Act I', label: 'Set-Up', guidance: 'Tour the hero\'s flawed status quo. Plant everything that needs fixing — the "six things that need change."', placeholder: 'e.g. The dead-end job, the unanswered calls from Mom…' },
            { group: 'Act I', label: 'Catalyst', guidance: 'The life-changing event that knocks over the first domino. There\'s no going back to before.', placeholder: 'e.g. The letter says she has 30 days to claim the inheritance…' },
            { group: 'Act I', label: 'Debate', guidance: 'The hero hesitates. Should I go? Can I do this? The question shows what they fear.', placeholder: 'e.g. She books the flight. Cancels it. Books it again…' },
            { group: 'Act II', label: 'Break Into Two', guidance: 'The hero chooses to act and enters the new world. Act II begins by decision, not accident.', placeholder: 'e.g. She lands on the island with one suitcase…' },
            { group: 'Act II', label: 'B Story', guidance: 'A new relationship (love interest, mentor, friend) that will carry the theme.', placeholder: 'e.g. The lighthouse keeper who knew her grandmother…' },
            { group: 'Act II', label: 'Fun and Games', guidance: 'The promise of the premise — the scenes on the poster. The hero explores the new world.', placeholder: 'e.g. Learning to sail, the town festival, the locked room…' },
            { group: 'Act II', label: 'Midpoint', guidance: 'A false victory or false defeat. Stakes raise, the fun ends, the clock starts ticking.', placeholder: 'e.g. She finds the will — and a second name on it…' },
            { group: 'Act II', label: 'Bad Guys Close In', guidance: 'Pressure mounts, internally and externally. Doubt, division, enemies regrouping.', placeholder: 'e.g. The developer\'s lawyers arrive; the keeper stops answering…' },
            { group: 'Act II', label: 'All Is Lost', guidance: 'The lowest point — the opposite of the Midpoint. Often carries a "whiff of death."', placeholder: 'e.g. The deed burns with the boathouse…' },
            { group: 'Act II', label: 'Dark Night of the Soul', guidance: 'The hero sits in defeat and confronts the theme. What do they truly need to learn?', placeholder: 'e.g. She packs her bag. Reads Mom\'s last unopened letter…' },
            { group: 'Act III', label: 'Break Into Three', guidance: 'The solution appears — usually by fusing the A story and B story lessons. The hero rises.', placeholder: 'e.g. The keeper\'s photos prove the forgery — but only if she stays…' },
            { group: 'Act III', label: 'Finale', guidance: 'The hero executes the plan, faces the antagonist, and proves they\'ve changed.', placeholder: 'e.g. The town meeting showdown…' },
            { group: 'Act III', label: 'Final Image', guidance: 'The "after" photo — the mirror of the Opening Image showing how much has changed.', placeholder: 'e.g. Sunday dinner, table for twelve…' },
        ],
    },
    {
        id: 'romancing-the-beat',
        name: 'Romancing the Beat',
        family: 'beat-sheet',
        formats: ['story'],
        tagline: 'The romance arc as its own 4-phase beat sheet, braided with the external plot.',
        bestFor: 'Romance novels and romantic subplots',
        beats: [
            { group: 'Phase 1: Setup', label: 'Introduce Lead One', guidance: 'Meet the first lead in their incomplete state. What hole in their life will love expose?', placeholder: 'e.g. A chef who tastes nothing since the accident…' },
            { group: 'Phase 1: Setup', label: 'Introduce Lead Two', guidance: 'Meet the second lead, equally incomplete in a complementary way.', placeholder: 'e.g. A food critic who\'s never cooked a meal…' },
            { group: 'Phase 1: Setup', label: 'Meet Cute', guidance: 'The leads collide. Sparks — of attraction, irritation, or both.', placeholder: 'e.g. She torches his review in front of the whole kitchen…' },
            { group: 'Phase 1: Setup', label: 'No Way', guidance: 'Both leads reject the possibility. Their inner demons say love is off the table.', placeholder: 'e.g. Never again with a critic. Never again with a chef…' },
            { group: 'Phase 1: Setup', label: 'Stuck Together', guidance: 'The adhesion: a reason they can\'t just walk away from each other.', placeholder: 'e.g. The magazine assigns them a joint column…' },
            { group: 'Phase 2: Falling', label: 'No Way, Redux', guidance: 'Proximity stirs feelings; both double down on denial.', placeholder: 'e.g. It\'s just professional. Strictly the column…' },
            { group: 'Phase 2: Falling', label: 'Inkling of Desire', guidance: 'A crack in the armor — the first honest moment of wanting.', placeholder: 'e.g. He notices she hums when she plates dessert…' },
            { group: 'Phase 2: Falling', label: 'Deepening Desire', guidance: 'The feelings grow undeniable in private, even while denied in public.', placeholder: 'e.g. Late-night market runs that neither calls a date…' },
            { group: 'Phase 2: Falling', label: 'Maybe This Could Work', guidance: 'Hope wins a round. The leads glimpse a future together.', placeholder: 'e.g. Cooking side by side, the kitchen finally quiet…' },
            { group: 'Phase 2: Falling', label: 'Midpoint of Love', guidance: 'The high-water mark — a kiss, a confession, a night. The demons go quiet. Briefly.', placeholder: 'e.g. The rooftop dinner she cooks just for him…' },
            { group: 'Phase 3: Retreating', label: 'Inkling of Doubt', guidance: 'The inner demons wake up. Old wounds whisper that this can\'t last.', placeholder: 'e.g. He drafts the review and can\'t press send…' },
            { group: 'Phase 3: Retreating', label: 'Deepening Doubt', guidance: 'Fear compounds. The leads start protecting themselves instead of each other.', placeholder: 'e.g. She catches him with his editor, assumes the worst…' },
            { group: 'Phase 3: Retreating', label: 'Retreat', guidance: 'Walls go up. The leads pull back into their old, safe patterns.', placeholder: 'e.g. Separate columns. Formal emails…' },
            { group: 'Phase 3: Retreating', label: 'Break Up', guidance: 'The relationship shatters — the romance\'s All Is Lost. The demons appear to have won.', placeholder: 'e.g. The review runs. Three stars. She reads it twice…' },
            { group: 'Phase 4: Fighting For Love', label: 'Dark Night', guidance: 'Each lead alone with the wreckage — and with the truth of what they lost.', placeholder: 'e.g. He eats alone. Everything tastes like her absence…' },
            { group: 'Phase 4: Fighting For Love', label: 'Epiphany', guidance: 'The realization: the demon was wrong. Love is worth the risk of the wound.', placeholder: 'e.g. Three stars: her food, his cowardice, their unfinished story…' },
            { group: 'Phase 4: Fighting For Love', label: 'Grand Gesture', guidance: 'One lead risks everything publicly to prove they\'ve changed.', placeholder: 'e.g. He retracts the review in print — and applies as her dishwasher…' },
            { group: 'Phase 4: Fighting For Love', label: 'Whole-Hearted Commitment', guidance: 'Both leads choose each other, demons and all. The new "us" is stronger than the old fears.', placeholder: 'e.g. She hands him a knife. "Stage one: you learn to chop."' },
            { group: 'Phase 4: Fighting For Love', label: 'Happily Ever After', guidance: 'Show the couple in their new equilibrium — the proof the arc is complete.', placeholder: 'e.g. One year later: a two-name sign over the door…' },
        ],
    },
    {
        id: 'seven-point',
        name: 'Seven-Point Structure',
        family: 'beat-sheet',
        formats: ['story', 'script'],
        tagline: 'Start at the resolution and build backward — hook and ending as mirrored opposites.',
        bestFor: 'Plotters who want structure without a full outline',
        starter: true,
        beats: [
            { label: 'Resolution', guidance: 'FILL THIS FIRST. Where does your character end up? The whole structure builds backward from here.', placeholder: 'e.g. She leads the rebellion she once informed on…' },
            { label: 'Hook', guidance: 'The mirror opposite of the Resolution. Show the character in their starting state — as far from the ending as possible.', placeholder: 'e.g. She reports her neighbors to keep her rations…' },
            { label: 'Plot Turn One', guidance: 'The event that moves the character from the Hook toward the Midpoint. The world changes; the journey begins.', placeholder: 'e.g. Her own name shows up on the watch list…' },
            { label: 'Pinch Point One', guidance: 'Apply pressure. Show the antagonist\'s power and force the character to act.', placeholder: 'e.g. The purge takes the family next door…' },
            { label: 'Midpoint', guidance: 'The character shifts from reaction to action. They stop running and start pushing back.', placeholder: 'e.g. She burns the informant files instead of delivering them…' },
            { label: 'Pinch Point Two', guidance: 'The vise closes. The antagonist strikes hardest; the character seems beaten and alone.', placeholder: 'e.g. Her handler reveals he\'s known for months…' },
            { label: 'Plot Turn Two', guidance: 'The character gains the final piece needed to win — the power was in them all along.', placeholder: 'e.g. The list of every informant — including the minister\'s son…' },
        ],
    },
    {
        id: 'story-spine',
        name: 'Story Spine',
        family: 'beat-sheet',
        formats: ['story', 'script', 'article'],
        tagline: 'The Pixar fill-in-the-blanks: "Once upon a time… because of that… until finally."',
        bestFor: 'Beginners, pitches, and testing whether a story hangs together causally',
        beats: [
            { label: 'Once upon a time…', guidance: 'Establish the world and the routine. Who lives here, and what is normal?', placeholder: 'e.g. Once upon a time, a robot sorted trash on an empty Earth…' },
            { label: 'Every day…', guidance: 'The repeated pattern. Show the routine that\'s about to be broken.', placeholder: 'e.g. Every day, he compacted cubes and collected treasures…' },
            { label: 'But one day…', guidance: 'The disruption — the event that breaks the routine and starts the story.', placeholder: 'e.g. But one day, a ship landed with a gleaming probe…' },
            { label: 'Because of that…', guidance: 'The first consequence. Each event must CAUSE the next — "and then" is not allowed.', placeholder: 'e.g. Because of that, he followed her to the sky…' },
            { label: 'Because of that…', guidance: 'The chain continues. Consequences compound and stakes grow.', placeholder: 'e.g. Because of that, the sleeping passengers began to wake…' },
            { label: 'Because of that…', guidance: 'The final link in the chain — the situation that forces the climax.', placeholder: 'e.g. Because of that, the captain fought the wheel for the ship…' },
            { label: 'Until finally…', guidance: 'The climax. The chain of consequences reaches its breaking point and resolves.', placeholder: 'e.g. Until finally, the plant touched soil again…' },
            { label: 'And ever since then…', guidance: 'The new normal. How is the world different because this story happened?', placeholder: 'e.g. And ever since then, green things grow where he wheels past…' },
        ],
    },

    // ── Fractal / expansion ──────────────────────────────────
    {
        id: 'snowflake',
        name: 'Snowflake Method',
        family: 'fractal',
        formats: ['story'],
        tagline: 'Grow a novel from one sentence — each step expands the last.',
        bestFor: 'Planners, complex plots, big casts',
        starter: true,
        beats: [
            { label: 'One-Sentence Summary', guidance: 'The whole story in ~15 words. No character names — "an X must Y or Z." This is your north star.', placeholder: 'e.g. A mapmaker must chart a country that redraws itself nightly or be erased with it.' },
            { label: 'One-Paragraph Summary', guidance: 'Expand to five sentences: setup, three disasters, ending. Each disaster forces the next act.', placeholder: 'e.g. Setup… First disaster… Second… Third… Resolution…' },
            { label: 'Character Summaries', guidance: 'One paragraph per major character: their goal, motivation, conflict, and epiphany. Every character thinks they\'re the protagonist.', placeholder: 'e.g. TESSA — wants the border fixed; believes maps are promises…' },
            { label: 'One-Page Synopsis', guidance: 'Expand each sentence of your paragraph into its own paragraph. The skeleton becomes a body.', placeholder: 'Expand each of your five sentences into a full paragraph…' },
            { label: 'Character Charts', guidance: 'Deepen each major character: backstory, voice, what they know and when. Contradictions welcome.', placeholder: 'e.g. TESSA — born the night of the first redrawing; lies about it…' },
            { label: 'Scene List', guidance: 'Break the synopsis into scenes — one line each: POV, what happens, what changes. This list becomes your draft roadmap.', placeholder: 'e.g. 1. Tessa (POV) discovers the eastern road missing — decides to hide it…' },
        ],
    },
    {
        id: 'mice-quotient',
        name: 'MICE Quotient',
        family: 'fractal',
        formats: ['story'],
        tagline: 'Four thread types — Milieu, Inquiry, Character, Event — nested and closed in reverse order.',
        bestFor: 'Short fiction and controlling nested subplots',
        beats: [
            { label: 'Milieu Thread', guidance: 'Opens when a character enters a place; closes when they leave or claim it. Travel, exploration, escape.', placeholder: 'e.g. OPEN: she boards the generation ship / CLOSE: she steps onto soil…' },
            { label: 'Inquiry Thread', guidance: 'Opens with a question; closes with its answer. Mysteries, investigations, secrets.', placeholder: 'e.g. OPEN: who erased the captain\'s log? / CLOSE: the log was never written…' },
            { label: 'Character Thread', guidance: 'Opens when a character becomes dissatisfied with who they are; closes when their identity settles.', placeholder: 'e.g. OPEN: he no longer believes in the mission / CLOSE: he redefines it…' },
            { label: 'Event Thread', guidance: 'Opens when the world\'s status quo breaks; closes when a new equilibrium holds. Disasters, wars, upheavals.', placeholder: 'e.g. OPEN: the engines fail / CLOSE: the ship becomes a station…' },
            { label: 'Nesting Order (FILO)', guidance: 'Close threads in REVERSE order of opening, like nested brackets: first opened is last closed. List your open/close order here and check it.', placeholder: 'e.g. Open: M → I → C … Close: C → I → M' },
        ],
    },
    {
        id: 'take-off-your-pants',
        name: 'Take Off Your Pants',
        family: 'fractal',
        formats: ['story'],
        tagline: 'A 14-beat outline grown from a character flaw — Truby distilled for fast drafting.',
        bestFor: 'Flaw-first, fast-drafting novelists',
        beats: [
            { label: 'Story Core', guidance: 'Five lines before anything else: your character / what they want / what opposes them / how they struggle / whether they succeed.', placeholder: 'e.g. A proud healer / wants to cure the plague / the church forbids it / she works in secret / she succeeds at exile\'s price.' },
            { group: 'Beginning', label: 'Opening Scene', guidance: 'Introduce the protagonist mid-life, with the flaw visible but unacknowledged.', placeholder: 'e.g. She turns away a beggar mid-sermon on charity…' },
            { group: 'Beginning', label: 'Display of Flaw', guidance: 'Show the flaw costing them something. The reader sees it; the character doesn\'t.', placeholder: 'e.g. Her pride loses her the apprenticeship…' },
            { group: 'Beginning', label: 'Inciting Event', guidance: 'The external plot arrives and hooks into the flaw like a burr.', placeholder: 'e.g. The first plague cart rolls past her door…' },
            { group: 'Middle', label: 'External Goal Formed', guidance: 'The character commits to a concrete external want — driven, secretly, by the flaw.', placeholder: 'e.g. She will find the cure alone and prove them all wrong…' },
            { group: 'Middle', label: 'Drive for the Goal', guidance: 'Pursuit. Progress happens, but the flaw contaminates every win.', placeholder: 'e.g. Each remedy works briefly; each ally is driven off…' },
            { group: 'Middle', label: 'Antagonist Revealed', guidance: 'The opposition clarifies — a person or force whose strength targets the flaw exactly.', placeholder: 'e.g. The inquisitor was her mentor once…' },
            { group: 'Middle', label: 'First Thwart', guidance: 'A serious defeat. The old approach fails publicly.', placeholder: 'e.g. Her clinic is burned with her notes inside…' },
            { group: 'Middle', label: 'Flaw Revisited', guidance: 'The character glimpses their flaw in the wreckage — and looks away. Not yet.', placeholder: 'e.g. "If they\'d only listened to me." But had she asked?…' },
            { group: 'Middle', label: 'New Drive', guidance: 'A changed plan with higher stakes. The flaw bends but doesn\'t break.', placeholder: 'e.g. She takes the cure underground, trusting exactly one person…' },
            { group: 'Middle', label: 'Antagonist Attacks', guidance: 'The opposition\'s strongest blow — aimed at what the character loves, not what they want.', placeholder: 'e.g. The inquisitor arrests her one trusted friend…' },
            { group: 'End', label: 'Second Thwart / Dark Moment', guidance: 'All is lost. The flaw\'s full price comes due at once.', placeholder: 'e.g. The friend won\'t see her. The cure sits useless…' },
            { group: 'End', label: 'Changed Goal', guidance: 'The epiphany: the character surrenders the flaw and the want transforms into the need.', placeholder: 'e.g. She gives the cure away — uncredited, unproven, free…' },
            { group: 'End', label: 'Triumph', guidance: 'The climax resolved by the changed character. Show the arc complete in action.', placeholder: 'e.g. The city heals under a hundred hands, none of them hers…' },
        ],
    },
];
